### ISSUE TITLE
Highlightable comments?

### ISSUE THREAD

**Issue by dongle-the-gadget** [itsWindows11/Carpeddit#20]
Looks like the comment section is highlightable.
<img width="911" alt="image" src="https://user-images.githubusercontent.com/29563098/178743556-d11bdaae-7a10-41a1-ad10-247cf7875eaa.png">

Maybe consider using something like `ItemsRepeater` instead of `TreeView`?

**Comment by itsWindows11** [comment]
I already fixed that, will push in the new release.
