### ISSUE TITLE
Bad request

### ISSUE THREAD

**Issue by muznyo** [itsWindows11/Carpeddit#26]
When i compile Carpeddit and log in, it shows this screen:
![image](https://user-images.githubusercontent.com/24987471/188312485-2178c4cf-ea7a-4595-8df5-95e17ad36441.png)

I use 2 factor authentication btw

**Comment by itsWindows11** [comment]
Try removing the ".compact" from the URL in the login page in the code and see if it works.

**Comment by muznyo** [comment]
same issue
![image](https://user-images.githubusercontent.com/24987471/188314951-28e7e362-ef9c-4603-af20-3abb4ab32b12.png)

**Comment by itsWindows11** [comment]
> same issue
> ![image](https://user-images.githubusercontent.com/24987471/188314951-28e7e362-ef9c-4603-af20-3abb4ab32b12.png)
> 

I'll try to investigate.

**Comment by itsWindows11** [comment]
![image](https://user-images.githubusercontent.com/81253203/188315223-fefa6eaa-cce1-494c-b0be-fa20ed114ca1.png)
Works for me, also have you followed the [building instructions](https://github.com/itsWindows11/Carpeddit/blob/main/CONTRIBUTING.md#running-the-app)?

**Comment by muznyo** [comment]
oh alright, it works now, the building instructions weren't in readme, so i missed it, thank you"
