### ISSUE TITLE
Is the project abandoned

### ISSUE THREAD

**Issue by foursplaysroblox** [itsWindows11/Carpeddit#32]
Just curious if it has been abandoned because it has not been updated for a while

**Comment by itsWindows11** [comment]
Nah it's not abandoned, I'm busy with some stuff irl and I'm currently working on other projects. I'll try getting back to it soon though don't worry.

**Comment by mediaexplorer74** [comment]
> ... I'll try getting back to it soon though don't worry.
> 
Hi. I have a very strange request for you. I'm a fan of Lumia winphones. All reddit customers are dead. Please help me create a minimal version of Carpeddit using the windows sdk 15063. All I need is an authorization mechanism. I tried to implement it myself, but I couldn't (  https://github.com/mediaexplorer74/CarpedditLite ).
